[project]
name = 'Decentralized-Atomic-Swap-Protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.Decentralized-Atomic-Swap-Protocol]
path = 'contracts/Decentralized-Atomic-Swap-Protocol.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
